source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AppFaqs_Example', :exclusive => true do
  pod "AppFaqs", :path => "../"
end

target 'AppFaqs_Tests', :exclusive => true do
  pod "AppFaqs", :path => "../"

  
end
